In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [2]:
dpath = 'jakarta_house_imputed.csv'
df = pd.read_csv(dpath)
df.head()

,index,price,district,city,bed_rooms,bath_rooms,carport,land_area,building_area
0,1,5900000000,Citra Garden,Jakarta Barat,2,4,2,250.0,350.0
1,2,2700000000,Jelambar,Jakarta Barat,4,2,0,100.0,225.0
2,3,2200000000,Jelambar,Jakarta Barat,3,3,0,60.0,140.0
3,4,1900000000,Jelambar,Jakarta Barat,3,2,0,60.0,120.0
4,5,2100000000,Tanjung Duren,Jakarta Barat,4,3,0,56.0,108.0

In [3]:
#slice data
df = df[['price', 'district', 'city', 'bed_rooms', 'bath_rooms', 'carport', 'land_area', 'building_area']]
df.head()

,price,district,city,bed_rooms,bath_rooms,carport,land_area,building_area
0,5900000000,Citra Garden,Jakarta Barat,2,4,2,250.0,350.0
1,2700000000,Jelambar,Jakarta Barat,4,2,0,100.0,225.0
2,2200000000,Jelambar,Jakarta Barat,3,3,0,60.0,140.0
3,1900000000,Jelambar,Jakarta Barat,3,2,0,60.0,120.0
4,2100000000,Tanjung Duren,Jakarta Barat,4,3,0,56.0,108.0

In [4]:
le = LabelEncoder() # membuat objek dari LabelEncoder
df['district'] = le.fit_transform(df['district']) # proses encoding
df['city'] = le.fit_transform(df['city']) # proses encoding

In [5]:
df.head()

,price,district,city,bed_rooms,bath_rooms,carport,land_area,building_area
0,5900000000,39,0,2,4,2,250.0,350.0
1,2700000000,74,0,4,2,0,100.0,225.0
2,2200000000,74,0,3,3,0,60.0,140.0
3,1900000000,74,0,3,2,0,60.0,120.0
4,2100000000,234,0,4,3,0,56.0,108.0

In [6]:
#standarisasi

std = StandardScaler()
df['price'] = std.fit_transform(df[['price']])

In [7]:
df.head()

,price,district,city,bed_rooms,bath_rooms,carport,land_area,building_area
0,-0.206558,39,0,2,4,2,250.0,350.0
1,-0.366205,74,0,4,2,0,100.0,225.0
2,-0.391150,74,0,3,3,0,60.0,140.0
3,-0.406117,74,0,3,2,0,60.0,120.0
4,-0.396139,234,0,4,3,0,56.0,108.0